name: flutter_helpful_codes
description: "A flutter/dart repo containing essential and helpful daily life code snippets to speed up development."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  package_info_plus:
  get:
  font_awesome_flutter:
  shared_preferences:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  # ASSETS
  assets:
    - assets/images/
    - assets/anims/

  # SANS FONT
  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf

    - family: SansBold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf

    - family: Adlam
      fonts:
        - asset: assets/fonts/ADLaMDisplay-Regular.ttf